USER02.YELPBUSINESS: CREATE TABLE ‘ USER02.YELPBUSINESS ’, ‘ BASE ’,
‘ATTRIBUTES’, ‘ HOURS ’                                              /*3 column families:BASE,ATTRIBUTES,HOURS*/

USER02.YELPCHECKIN: CREATE TABLE ‘ USER02.YELPCHECKIN ’, ‘ PERHOUR ’ /*1 column family:PERHOUR*/
